import type { EditorMaterial, SceneObject } from './types';

export const INITIAL_OBJECTS: SceneObject[] = [
  {
    uuid: 'object-brain',
    name: 'Cerebro',
    kind: 'model',
    source: '/human_brain.glb',
    sourceType: 'public',
    position: [-1.15, 0, 0],
    rotation: [0, 0, 0],
    scale: [1, 1, 1],
    visible: true,
    parent: null,
    materialId: 'material-brain',
    createdAt: 0,
  },
  {
    uuid: 'object-bulb',
    name: 'Lampada',
    kind: 'model',
    source: '/light_bulb.glb',
    sourceType: 'public',
    position: [1.65, 0, 0],
    rotation: [0, 0, 0],
    scale: [0.85, 0.85, 0.85],
    visible: true,
    parent: null,
    materialId: 'material-bulb',
    createdAt: 1,
  },
];

export const INITIAL_MATERIALS: Record<string, EditorMaterial> = {
  'material-brain': {
    uuid: 'material-brain',
    objectId: 'object-brain',
    name: 'Material Cerebro',
    color: '#dbeafe',
    metalness: 0.05,
    roughness: 0.58,
    emissive: '#082f49',
    emissiveIntensity: 0.45,
    opacity: 1,
    textureUrl: null,
    textureName: null,
  },
  'material-bulb': {
    uuid: 'material-bulb',
    objectId: 'object-bulb',
    name: 'Material Lampada',
    color: '#fff4bd',
    metalness: 0.12,
    roughness: 0.24,
    emissive: '#f59e0b',
    emissiveIntensity: 0.35,
    opacity: 1,
    textureUrl: null,
    textureName: null,
  },
};
